# Generated by Django 3.2.4 on 2021-06-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoMovimiento', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoUsuario', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=60)),
                ('apellidoUsuario', models.CharField(max_length=120)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('capitalTotal', models.DecimalField(decimal_places=10, max_digits=20)),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_control.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionMovimiento', models.TextField()),
                ('valorMovimiento', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fechaMovimiento', models.DateTimeField()),
                ('tipoMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_control.tipomovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_control.usuario')),
            ],
        ),
    ]
