# Generated by Django 3.2.1 on 2021-07-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0003_auto_20210705_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fechaMovimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='valorMovimiento',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='capitalTotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
