# Generated by Django 3.2.1 on 2021-07-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0004_auto_20210706_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deudas',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
