# Generated by Django 3.2.1 on 2021-07-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0005_profile_deudas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deudas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
