# Generated by Django 3.2.1 on 2021-07-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0007_auto_20210712_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deudas',
        ),
    ]
