# Generated by Django 4.1.1 on 2022-09-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_control', '0008_remove_profile_deudas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionMovimientoProgramado', models.TextField()),
                ('valorMovimientoProgramado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaMovimientoProgramado', models.DateField()),
                ('tipoMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_control.tipomovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
