# Generated by Django 4.1.1 on 2022-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0010_alter_programador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador',
            name='ultimafechaEjecucion',
            field=models.DateField(null=True),
        ),
    ]
