# Generated by Django 4.1.1 on 2022-09-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0011_programador_ultimafechaejecucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programador',
            old_name='ultimafechaEjecucion',
            new_name='ultimaFechaEjecucion',
        ),
    ]
