# Generated by Django 4.1.1 on 2023-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0012_rename_ultimafechaejecucion_programador_ultimafechaejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='fechaMovimientoProgramado',
            field=models.PositiveIntegerField(),
        ),
    ]
