# Generated by Django 4.1.1 on 2023-01-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0015_alter_programador_fechamovimientoprogramado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='fechaMovimientoProgramado',
            field=models.SmallIntegerField(),
        ),
    ]
