# Generated by Django 4.1.1 on 2023-01-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_control', '0017_alter_programador_fechamovimientoprogramado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programador',
        ),
    ]
