# Generated by Django 4.1.1 on 2023-01-23 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_control', '0018_delete_programador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionMovimientoProgramado', models.TextField()),
                ('valorMovimientoProgramado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fechaMovimientoProgramado', models.DateField()),
                ('ultimaFechaEjecucion', models.DateField(null=True)),
                ('tipoMovimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_control.tipomovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
